#!/usr/bin/env bash
# auto_ponytail.sh — DEBT / GAIN / REVIEW snapshot of this repo.
#
# Our own implementation of the ponytail ladder in AGENTS.md: classify what is
# here as DEBT (dead code, docs that lie, bugs sitting in an existing path),
# GAIN (something impossible today) or fine. It is a reader, not an editor: it
# writes one report and touches nothing else.
#
# Why it can be trusted: every check is either exact or it says so. Where a check
# has known false positives the report names them rather than presenting guesses
# as findings. A linter that cries wolf gets ignored, which is worse than none.
#
# Usage:
#   scripts/auto_ponytail.sh              # write docs/auto-ponytail.md, print it
#   scripts/auto_ponytail.sh --quiet      # print the summary only
#
# Exit code: always 0. This is advisory; it never gates anything.

set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO/docs/auto-ponytail.md"
QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1

say() { [ "$QUIET" = "1" ] || printf '%s\n' "$*"; }

cd "$REPO" || exit 0

# Tracked files only. Build output, node_modules and the report itself are noise.
tracked() { git ls-files "$@"; }

# ── DEBT 1: source files nothing imports ───────────────────────────────────────
# Exact for this tree: there are no dynamic imports and no glob loading, and every
# import specifier is a literal. Vite resolves extensionless (`from "../core/anim"`),
# so match the stem, not the basename.
# False positives: entry points, and CSS imported by a module that only appears in
# an index.html (handled below).
referenced_modules() {
  tracked 'app/src/*' 'app/src/*/*' \
  | grep -E '\.(ts|css)$' \
  | while read -r f; do
      base="$(basename "$f")"
      stem="${base%.*}"
      case "$base" in main.ts|settings.css|index.html) continue ;; esac
      # Any specifier ending in /<stem> or ./<stem>, with or without extension.
      if grep -rqE "(from|import) [\"'][^\"']*/?${stem}(\.[a-z]+)?[\"']" app/src 2>/dev/null; then
        continue
      fi
      # CSS pulled in by an HTML entry point rather than by a module.
      if [ "${base##*.}" = "css" ] \
         && grep -rq "$base" app/*.html 2>/dev/null; then
        continue
      fi
      echo "$f"
    done
}

# ── DEBT 2: docs naming files that are not in the tree ────────────────────────
# This is the check that catches the failure mode that actually bit us: a spec
# pointing at windows/, or at a binary that was renamed.
# False positives: glob paths, globs in prose, and paths that exist upstream but
# were deliberately deleted here (those are listed, not failed).
doc_missing_paths() {
  tracked '*.md' \
  | while read -r doc; do
      grep -oE '(app|scripts|docs|shared)/[A-Za-z0-9_./-]+\.(rs|ts|sh|html|md|wav|json|css)' "$doc" 2>/dev/null \
      | sort -u \
      | while read -r ref; do
          [ -e "$REPO/$ref" ] || echo "$doc|$ref"
        done
    done
}

# ── DEBT 3: deferred markers, grouped by file ─────────────────────────────────
todo_markers() {
  tracked 'app/src/*' 'app/src-tauri/src/*' 'app/hook/src/*' 'scripts/*' 'docs/*.md' \
  | while read -r f; do
      n="$(grep -ciE '\b(TODO|FIXME|XXX|HACK)\b' "$f" 2>/dev/null || true)"
      [ "${n:-0}" -gt 0 ] && printf '%3d  %s\n' "$n" "$f"
    done | sort -rn
}

# ── DEBT 4: tracked scripts no doc or workflow mentions ───────────────────────
orphan_scripts() {
  tracked 'scripts/*' \
  | while read -r s; do
      base="$(basename "$s")"
      grep -rql --exclude-dir=.git --exclude-dir=node_modules -- "$base" \
        README.md docs .github AGENTS.md CLAUDE.md CONTRIBUTING.md 2>/dev/null \
        || echo "$s"
    done
}

# ── DEBT 5: Rust items muted as dead code ─────────────────────────────────────
# Each one is a claim that something is unused. Some are honest (serde derive,
# public API surface); a growing count is the smell.
allow_dead_code() {
  grep -rn --include='*.rs' '#\[allow(dead_code)\]' app/src-tauri/src app/hook/src 2>/dev/null \
    | sed "s|$REPO/||"
}

# ── collect ────────────────────────────────────────────────────────────────────
MODS="$(referenced_modules | sort -u)"
DOCS="$(doc_missing_paths | sort -u)"
ORPHANS="$(orphan_scripts | sort -u)"
DEFERRED="$(todo_markers)"
MUTED="$(allow_dead_code)"

count() { [ -z "$1" ] && echo 0 || printf '%s\n' "$1" | grep -c . ; }

N_MODS=$(count "$MODS"); N_DOCS=$(count "$DOCS")
N_ORPHANS=$(count "$ORPHANS"); N_MUTED=$(count "$MUTED")

{
  echo "# auto-ponytail"
  echo
  echo "Generated by \`scripts/auto_ponytail.sh\`. Do not edit — it is overwritten."
  echo "Snapshot of $(git rev-parse --short HEAD 2>/dev/null || echo '?') on $(date +%Y-%m-%d)."
  echo
  echo "| | count |"
  echo "|---|---|"
  echo "| DEBT · modules nothing imports | $N_MODS |"
  echo "| DEBT · doc paths that do not exist | $N_DOCS |"
  echo "| DEBT · scripts no doc mentions | $N_ORPHANS |"
  echo "| DEBT · \`#[allow(dead_code)]\` claims | $N_MUTED |"
  echo

  echo "## DEBT · modules nothing imports"
  echo
  if [ -n "$MODS" ]; then
    echo "$MODS" | sed 's/^/- `/;s/$/`/'
    echo
    echo "_Candidates only._ A module reached by a dynamic import or referenced only"
    echo "from a doc is a false positive; check before deleting."
  else
    echo "None."
  fi
  echo

  echo "## DEBT · doc paths that do not exist"
  echo
  if [ -n "$DOCS" ]; then
    printf '%s\n' "$DOCS" | sed 's/|/ → `/;s/$/`/'
    echo
    echo "_Deliberately deleted paths are expected to show up here_ (this fork removed"
    echo "\`NotchBuddy/\` and \`windows/\`). Only entries naming something that should"
    echo "exist are real."
  else
    echo "None."
  fi
  echo

  echo "## DEBT · scripts no doc mentions"
  echo
  if [ -n "$ORPHANS" ]; then
    echo "$ORPHANS" | sed 's/^/- `/;s/$/`/'
  else
    echo "None."
  fi
  echo

  echo "## DEBT · deferred markers"
  echo
  if [ -n "$DEFERRED" ]; then
    echo '```'
    echo "$DEFERRED"
    echo '```'
    echo
    echo "_A marker deferred twice is a delete candidate, not a TODO._ (AGENTS.md)"
  else
    echo "None."
  fi
  echo

  echo "## DEBT · \`#[allow(dead_code)]\`"
  echo
  if [ -n "$MUTED" ]; then
    echo '```'
    echo "$MUTED"
    echo '```'
    echo
    echo "_Each line is a claim that something is unused. Honest for serde derives; a"
    echo "growing count is the smell._"
  else
    echo "None."
  fi
  echo

  echo "## What this deliberately does not check"
  echo
  echo "- **Whether the app works.** That is \`scripts/verify_coucou_linux.sh\`, which"
  echo "  runs live probes and reports PASS/FAIL/SKIP."
  echo "- **Upstream sync state.** \`scripts/sync_upstream.sh --check\` does that, and"
  echo "  writes \`SYNC-TODO.md\`."
  echo "- **Anything requiring the network.** This runs offline and in seconds."
  echo "- **Code quality, style, or GAIN.** 'Would this be nicer' is a judgement, and"
  echo "  a script that makes it is a script whose opinions outlive its usefulness."
} > "$OUT"

say "auto-ponytail → ${OUT#$REPO/}"
say ""
say "DEBT  modules nothing imports : $N_MODS"
say "DEBT  doc paths that do not exist: $N_DOCS"
say "DEBT  scripts no doc mentions  : $N_ORPHANS"
say "DEBT  allow(dead_code) claims  : $N_MUTED"
[ "$QUIET" = "1" ] || say ""
[ "$QUIET" = "1" ] || say "Full report: ${OUT#$REPO/}"
exit 0
